#!/bin/bash -e

cat $1 |
while read line; do echo -n $line' '; done |
sed -r '
s/ *<\?.*?\?> *//;
s/ *<!--.*?--> *//g;
s/(\.[0-9]{,2})[0-9]*/\1/g;
s/ (xmlns|sodipodi|inkscape):[a-z]+="[^"]+"//g;
s/xlink://g;
s/<\/?(xmlns|sodipodi|inkscape)[^>]*>//g;
s/style="[^"]*(fill:....)[^"]*(;stroke-width:....)[^"]*(;stroke:....)[^"]*"/style="\1\2"/g;
s/ id="[^_][^"]*"//g;
s/ +/ /g;
s/> </></g;
'
